### ISSUE TITLE
Lightning Status

### ISSUE THREAD

**Issue by faroit** [tmbdev-archive/webdataset-examples#2]
@tmbdev just checking with you to get some clarification of the current state of the lightning imagenet example

> NB: this example needs updating and may not work with the latest versions of Lightning and WebDataset

- Is this still the case? 
- What is the last version of lightning that was tested for this example? 
- What about freezing the lightning version to that version?
- Do you have have path to clear the remaining issues with newer lightning versions? Anything where we could contribute?

**Comment by tmbdev** [comment]
The "dev" branch is heavily revised and every component just implements standard IterableDataset. It also provides an easy to create custom URL splits. There is an example in the docs of how that works. With that it should be easy to customize it for Lightning. The "dev" branch will become the new main branch in a couple of weeks.

I still need to put together a working Lightning example (nobody around here uses Lightning, so it takes a little while to get that set up and running again).

**Comment by austinmw** [comment]
@tmbdev Hi, any updates on Lightning example?

**Comment by tmbdev** [comment]
The WebDataset library has been updated to deal better with DDP, so things should work better out of the box.

I'll try to create a separate example for Lightning and put it in webdataset-lightning.

**Comment by tmbdev** [comment]
Have a look at http://github.com/tmbdev/webdataset-lightning
